### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by arne-cl** [kaayy/josydipa#1]
Dear Kai,

in your paper [Joint Syntacto-Discourse Parsing and the Syntacto-Discourse Treebank
](https://arxiv.org/pdf/1708.08484.pdf) this repo is given as a link. I could not find the source
code to the parser here. Is it published somewhere else?

Best regards,
Arne

**Comment by kaayy** [comment]
Hi Arne,

I am very glad to know that you are interested in our paper. Actually I am still working on cleaning up the code and dataset. Hopefully I can upload the code in the coming couple of weeks.

Thanks!

Regards,
Kai

**Comment by kaayy** [comment]
Hi Arne,

The code for the parser has been uploaded. Just let me know if you have any questions!

Regards,
Kai
